version: 1
disable_existing_loggers: False

formatters:
  rest:
    format: '%(asctime)-23s %(name)s-%(module)-15s %(funcName)-23s %(levelname)-10s %(message)s'

handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: rest
        filename: /tmp/y-bot.log

root:
    level: DEBUG
    handlers:
        - file
